backend:
  name: github
  repo: mdown-kar/coffee-website # replace with your GitHub username/repo
  branch: main

media_folder: "./images" # Folder for uploaded images
public_folder: "/images" # Path used in the site

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "string" }
